version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - 8000:80
        networks:
            - symfony

networks:
    symfony:
