version: '3'

services:
    database:
        image: postgres:12.4
        container_name: crm_db
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        networks:
            - symfony
        volumes:
            - ./dbdata:/var/lib/postgresql/data
    php-fpm:
        container_name: crm_php
#        links:
#            - database
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/
        networks:
            - symfony
#        depends_on:
#            - database
    nginx:
        container_name: crm_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - 8000:80
        networks:
            - symfony

    composer:
        image: composer
        command: ["composer", "install", "--no-ansi", "--ignore-platform-reqs"]
        volumes:
            - ./composer.lock:/app/composer.lock
            - ./composer.json:/app/composer.json
            - ./vendor:/app/vendor

networks:
    symfony:
